### ISSUE TITLE
enhance readme

### ISSUE THREAD

**Issue by pinak22dhir** [swiftwave-org/swiftwave#154]
### Is your feature request related to a problem? Please describe

readme by adding pics

### Describe the solution you'd like

enhance readme by documentation

### Are you working on this?

Yes

**Comment by tanmoysrt** [comment]
Hi @pinak22dhir

Currently, we have delayed the readme update because we haven't update `swiftwave dashboard` till now. 

we are designing our documentation with docusaurus.
https://github.com/swiftwave-org/swiftwave.org

We have recently added CLI in our software, so would you like to add documentation for the CLI?

**Comment by pinak22dhir** [comment]
sure @tanmoysrt

**Comment by tanmoysrt** [comment]
Hi @pinak22dhir 
Can you join our slack channel
https://join.slack.com/t/swiftwave-team/shared_invite/zt-21n86aslx-aAvBi3hv1GigVA_XoXiu4Q

I will share a google docs with you for the CLI to have base documentation

**Comment by tanmoysrt** [comment]
Hi @pinak22dhir 

You can refer this one to write the documentation !
[cli_docs.zip](https://github.com/swiftwave-org/swiftwave/files/13688905/cli_docs.zip)

**Comment by tanmoysrt** [comment]
Completed :ok:
