### ISSUE TITLE
feat: Docs Improvement in regards to cluster mode

### ISSUE THREAD

**Issue by samuel-108** [swiftwave-org/swiftwave#906]
### Is your feature request related to a problem? Please describe

It'd be great if there were more information on how the cluster mode works.

- What is a manager node vs worker node?
- How many manager node can there be?
- Why activate proxy?
- If there are 2 active proxy server, which one to point IP at? Which one is better to point IP at? Should there be 2 active proxy servers?
- Why does the manager node sometimes show as being gone down, while I can still SSH into it?

### Describe the solution you'd like

Added documentation in regards to clarity on the cluster mode

### Are you working on this?

No

**Comment by tanmoysrt** [comment]
Thanks @samuel-108 for reporting

**Comment by tanmoysrt** [comment]
**Why does the manager node sometimes show as being gone down, while I can still SSH into it?**

For any task in **swiftwave** it has a SSH pool setup, so it opens a single connection and create sessions for various task. Because creating multiple TCP connection is too much resource consuming. With some cloud provider, which have frequent SSH timeout, it drops the connection.

In **swiftwave**, it has program for backup the connection. It should backup connection within 2 minutes but it takes longer time. I am still searching for the actual root cause of that. 

For **SSH to Server**, it doesn't use that SSH Pool, instead it create new TCP connection as we don't expect multiple SSH terminal at same time. That's why while it shows down, still you can SSH to server.

**Comment by samuel-108** [comment]
Ahh, I see thank you for the explanation.
