### ISSUE TITLE
bug: CIFS backups resulting on faulty files (unable to decompress the backups)

### ISSUE THREAD

**Issue by samuel-108** [swiftwave-org/swiftwave#909]
### Describe the bug

The CIFS mounted volume's backups are resulting in faulty archives. 

<img width="482" alt="Screenshot 2024-07-01 at 10 40 12 AM" src="https://github.com/swiftwave-org/swiftwave/assets/172349572/a9218655-9e2c-4630-88cb-ea55d16eaee0">

### Are you working on this issue?

No

**Comment by samuel-108** [comment]
The problem exist on following cases on Local mount as well
- Run a filebrowser instance
- While still running try to back up the filebrowser db volume
- The backup comes out corrupted

**Comment by samuel-108** [comment]
This only seems to occour when sqlite files are in the folder. Am unsure of any further issue beside faulty backups.

**Comment by tanmoysrt** [comment]
@samuel-108 thanks for reporting the issue.

Can you tryout this.
- Pause (or delete for testing) the filebrowser app from dashboard
- Then, create the backup

P.S: Because previously, I found that, while container is up, if we take backup of sqlite, it comes as corrupted. I haven't seen this for any SQL database(Mysql , postgres physical backup)

**Comment by tanmoysrt** [comment]
The logic is pretty simple behind this backup, we just run 
```bash
tar -xzvf dump.tar.gz --directory <your_directoory>
```

to dump the volume to a file, then swiftwave manages to take it on main node (if required)

**Comment by samuel-108** [comment]
I see,

It does seem to work when the container is turned off.
