### ISSUE TITLE
bug: register a new domain

### ISSUE THREAD

**Issue by maximehamou** [swiftwave-org/swiftwave#945]
### Describe the bug

Hello,
I need to register a subdomain in my swiftwave dashboard. I've pointed the subdomain to the server IP address, but when I click on `Verify DNS`, I have the error message : `DNS for domain.zakine-avocats.fr is not pointed correctly`.
Does anyone knows what do I have to do to register the domain correctly?
Thanks.

### Are you working on this issue?

Yes

**Comment by MaxMorais** [comment]
I'm having the same issue!

**Comment by tanmoysrt** [comment]
> I'm having the same issue!

Ir can be due to two reason -
1. Proxy is down. If it's the case, proxy should be up automatically. Or from server list disable proxy, wait 5 minutes and re-enable it.
2. Old DNS info cached in your server or DNS info still not propagated everywhere. In this case, you need to wait for hours to fix that. Flushing your domain from popular DNS resolvers make it faster.

   - https://dns.google/cache
   - https://one.one.one.one/purge-cache/
   - SSH to your server & run `systemd-resolve --flush-caches` (you can do it from swiftwave server list > Actions > Web console too)
